import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f5faff",
        "surface-dim": "#d6dbdf",
        "surface-bright": "#f5faff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4f9",
        "surface-container": "#eaeef3",
        "surface-container-high": "#e4e9ee",
        "surface-container-highest": "#dee3e8",
        "surface-variant": "#dee3e8",
        "on-surface": "#171c20",
        "on-surface-variant": "#3e484f",
        primary: "#00668a",
        "on-primary": "#ffffff",
        "primary-container": "#38bdf8",
        "on-primary-container": "#004965",
        "primary-fixed": "#c4e7ff",
        "primary-fixed-dim": "#7bd0ff",
        "on-primary-fixed": "#001e2c",
        "on-primary-fixed-variant": "#004c69",
        secondary: "#4648d4",
        "on-secondary": "#ffffff",
        "secondary-container": "#6063ee",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e1e0ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#07006c",
        "on-secondary-fixed-variant": "#2f2ebe",
        tertiary: "#855300",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#f1a02b",
        "on-tertiary-container": "#613b00",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb960",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        background: "#f5faff",
        "on-background": "#171c20",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        outline: "#6e7980",
        "outline-variant": "#bdc8d1",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        "t-xs": "8px",
        "t-sm": "16px",
        "t-md": "24px",
        "t-lg": "40px",
        "t-xl": "64px",
        gutter: "24px",
        margin: "32px",
      },
      animation: {
        float: "float 4s ease-in-out infinite",
        scan: "scan 3s linear infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-4px)" },
        },
        scan: {
          "0%": { top: "0%" },
          "100%": { top: "100%" },
        },
      },
      backgroundImage: {
        "aura-gradient": "radial-gradient(circle at 0% 0%, rgba(56, 189, 248, 0.15) 0%, transparent 50%), radial-gradient(circle at 100% 100%, rgba(132, 85, 239, 0.1) 0%, transparent 50%), radial-gradient(circle at 50% 50%, rgba(248, 249, 255, 1) 0%, rgba(229, 238, 255, 1) 100%)",
      },
    },
  },
  plugins: [],
};
export default config;
